aircraft_index:
    path:     /
    defaults: { _controller: "OnicFlightInventoryBundle:Aircraft:index" }
    methods:  GET

aircraft_show:
    path:     /{id}/show
    defaults: { _controller: "OnicFlightInventoryBundle:Aircraft:show" }
    methods:  GET

aircraft_new:
    path:     /new
    defaults: { _controller: "OnicFlightInventoryBundle:Aircraft:new" }
    methods:  [GET, POST]

aircraft_edit:
    path:     /{id}/edit
    defaults: { _controller: "OnicFlightInventoryBundle:Aircraft:edit" }
    methods:  [GET, POST]

aircraft_delete:
    path:     /{id}/delete
    defaults: { _controller: "OnicFlightInventoryBundle:Aircraft:delete" }
    methods:  DELETE
