booking_index:
    path:     /
    defaults: { _controller: "OnicFlightInventoryBundle:Booking:index" }
    methods:  GET

booking_show:
    path:     /{id}/show
    defaults: { _controller: "OnicFlightInventoryBundle:Booking:show" }
    methods:  GET

booking_new:
    path:     /new
    defaults: { _controller: "OnicFlightInventoryBundle:Booking:new" }
    methods:  [GET, POST]

booking_edit:
    path:     /{id}/edit
    defaults: { _controller: "OnicFlightInventoryBundle:Booking:edit" }
    methods:  [GET, POST]

booking_delete:
    path:     /{id}/delete
    defaults: { _controller: "OnicFlightInventoryBundle:Booking:delete" }
    methods:  DELETE
