flight_index:
    path:     /
    defaults: { _controller: "OnicFlightInventoryBundle:Flight:index" }
    methods:  GET

flight_show:
    path:     /{id}/show
    defaults: { _controller: "OnicFlightInventoryBundle:Flight:show" }
    methods:  GET

flight_new:
    path:     /new
    defaults: { _controller: "OnicFlightInventoryBundle:Flight:new" }
    methods:  [GET, POST]

flight_edit:
    path:     /{id}/edit
    defaults: { _controller: "OnicFlightInventoryBundle:Flight:edit" }
    methods:  [GET, POST]

flight_delete:
    path:     /{id}/delete
    defaults: { _controller: "OnicFlightInventoryBundle:Flight:delete" }
    methods:  DELETE
