onic_flight_inventory_airline:
    resource: "@OnicFlightInventoryBundle/Resources/config/routing/fiairline.yml"
    prefix:   /airline

onic_flight_inventory_aircraft:
    resource: "@OnicFlightInventoryBundle/Resources/config/routing/fiaircraft.yml"
    prefix:   /aircraft

onic_flight_inventory_flight:
    resource: "@OnicFlightInventoryBundle/Resources/config/routing/fiflight.yml"
    prefix:   /flight

onic_flight_inventory_passenger:
    resource: "@OnicFlightInventoryBundle/Resources/config/routing/fipassenger.yml"
    prefix:   /passenger

onic_flight_inventory_booking:
    resource: "@OnicFlightInventoryBundle/Resources/config/routing/fibooking.yml"
    prefix:   /booking

onic_flight_inventory_location:
    resource: "@OnicFlightInventoryBundle/Resources/config/routing/filocation.yml"
    prefix:   /location

onic_flight_inventory_homepage:
    path:     /
    defaults: { _controller: OnicFlightInventoryBundle:Default:index }
