onic_flight_inventory_admin:
    resource: "@OnicFlightInventoryBundle/Resources/config/routing/admin_routing.yml"
    prefix:   /admin

onic_flight_inventory_frontend:
    resource: "@OnicFlightInventoryBundle/Resources/config/routing/frontend_routing.yml"
    prefix:   /

location_autocomplete:
    path:     /autocomplete
    defaults: { _controller: "OnicFlightInventoryBundle:Location:autocomplete" }
    methods:  GET

onic_flight_inventory_homepage:
    path:     /
    defaults: { _controller: OnicFlightInventoryBundle:Frontend:index }
