services:
#    onic_flight_inventory.example:
#        class: Onic\FlightInventoryBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
    onic_flight_inventory.flighttype:
        class: Onic\FlightInventoryBundle\Form\FiFlightType
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: form.type }